server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 8096
  port: 80
debug: true

spring:
  cache:
    # 使用了Spring Cache后，能指定spring.cache.type就手动指定一下，虽然它会自动去适配已有Cache的依赖，但先后顺序会对Redis使用有影响（JCache -> EhCache -> Redis -> Guava）
    type: REDIS
  redis:
    host: 127.0.0.1
    port: 6379
    # password:  默认没有密码，生产环境一定要设置密码
    # 连接超时时间（ms）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/Meow
    username: root
    password: CAOshunmiao
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      idle-timeout: 100000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis-plus:
  # 在classpath前添加星号可以使项目热加载成功<br>  # 自定义xml sql文件需要配置这个
  mapper-locations: classpath:mapper/*.xml
  global-config:
    #机器 ID 部分(影响雪花ID)
    #workerId: 1
    #数据标识 ID 部分(影响雪花ID)(workerId 和 datacenterId 一起配置才能重新初始化 Sequence)
    #datacenterId: 18
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #field-strategy: 2
    #驼峰下划线转换
    #db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    db-config:
      #主键类型
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: xyz.javaee.blog
#    配置基础包名

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

# 配置你的七牛云
qi-niu:
  access-key:
  secret-key:
  bucket:
